### ISSUE TITLE
not refreshing data into homeAssistant

### ISSUE THREAD

**Issue by oussamaghanem** [jacokok/must-ep1800#1]
thank you for your effort in this app
but found not not refreshing data into HomeAssistant mqtt
however as per your config ,should be updated every 5 minutes thought?
MUST_Config__Cron='0 0/5 * * * ?'

thank you

**Comment by oussamaghanem** [comment]
Sorry solved problem from my side ,created service and as per diagnostic found that on each  restart and new docker container image created...
Multiple conflict, solved by a shell script to start the desired docker at boot

**Comment by oussamaghanem** [comment]
But found some issues related to home assistant portal ,for the animated energy sources required calss:energy for some entity to
friendly_name: must-inverter_AccumulatedChargerPower
unit_of_measurement: kWh
device_class: energy

So found just accept entities in  kwh and class energy  to display the animated flow for  grid,Solar,battery and home

Please advise

**Comment by jacokok** [comment]
Hi,

In order for these entities to show up on energy page they also need state_class added to them.
I only included AccumulatedLoadPower as that was the only one I used.

https://developers.home-assistant.io/docs/core/entity/sensor/#available-state-classes

My AccumulatedChargerPower is always 0 but I could add that extra state_class to make it available on energy dashboard.

**Comment by jacokok** [comment]
You could use something like MQTT Explorer and change the config directly for the fields you need.
After that I could make the changes upstream. Example adding state_class to accumulatedChargerPower.

```json
{
  "name": "must-inverter_AccumulatedChargerPower",
  "unit_of_measurement": "kWh",
  "state_topic": "homeassistant/sensor/must-inverter/AccumulatedChargerPower",
  "icon": "mdi:chart-bell-curve-cumulative",
  "device_class": "energy",
  "state_class": "total_increasing"
}
```

**Comment by jacokok** [comment]
I added the extra state_class property to some more energy entities.

Just run a docker pull and run same commands again.
```bash
docker pull doink/must-ep1800
```

**Comment by oussamaghanem** [comment]
Thank you Dear,

As per you instructions

Action done:
Docker pulled
Binaries updated
Docker compose rebuilt
But just one entity still showed at the energy dashboard,
Did i missed some more actions to re-list the newly modified entities

Regards

________________________________

**Comment by jacokok** [comment]
Tested on my side and it showed up.

If you are using binaries make sure you also do a git pull.
Since this is pushed to docker hub you can just use latest image from there.

You are most likely either running an older version or you have errors. Check your container logs.

**Comment by oussamaghanem** [comment]
solved but can  we add the following for the grid and solar
        new RegisterTopic { Name = "AccumulatedChargerPower", UnitOfMeasurement = "kWh", Icon = "chart-bell-curve-cumulative", DeviceClass = "energy", StateClass = "total_increasing" },
        new RegisterTopic { Name = "AccumulatedDischargerPower", UnitOfMeasurement = "kWh", Icon = "chart-bell-curve-cumulative", DeviceClass = "energy", StateClass = "total_increasing" },
        new RegisterTopic { Name = "AccumulatedBuyPower", UnitOfMeasurement = "kWh", Icon = "chart-bell-curve-cumulative", DeviceClass = "energy", StateClass = "total_increasing" },
        new RegisterTopic { Name = "AccumulatedSellPower", UnitOfMeasurement = "kWh", Icon = "chart-bell-curve-cumulative" , DeviceClass = "energy", StateClass = "total_increasing" },
        new RegisterTopic { Name = "AccumulatedLoadPower", UnitOfMeasurement = "kWh", Icon = "chart-bell-curve-cumulative", DeviceClass = "energy", StateClass = "total_increasing" },
        new RegisterTopic { Name = "AccumulatedSelfusePower", UnitOfMeasurement = "kWh", Icon = "chart-bell-curve-cumulative", DeviceClass = "energy", StateClass = "total_increasing" },
        new RegisterTopic { Name = "AccumulatedPvsellPower", UnitOfMeasurement = "kWh", Icon = "chart-bell-curve-cumulative" , DeviceClass = "energy", StateClass = "total_increasing" },
        new RegisterTopic { Name = "AccumulatedGridChargerPower", UnitOfMeasurement = "kWh", Icon = "chart-bell-curve-cumulative" , DeviceClass = "energy", StateClass = "total_increasing" },
        new RegisterTopic { Name = "AccumulatedPvPower", UnitOfMeasurement = "kWh", Icon = "chart-bell-curve-cumulative" , DeviceClass = "energy", StateClass = "total_increasing" }
________________________________

**Comment by jacokok** [comment]
Sure I can make the change. Only saw this now because I closed the issue.

https://github.com/jacokok/must-ep1800/issues/2

**Comment by oussamaghanem** [comment]
Dear sir,
Expected to fixed the entities as per attached snapshot,
Thank you again

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by oussamaghanem** [comment]
Sorry I mean to check the flow as per attached photo
[cid:1726b34e-8ea2-4555-8b5c-37ad1e97fed4]
________________________________

**Comment by oussamaghanem** [comment]
Thank you ,really good work, hope if it can be done soon.
best Regards

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
