### ISSUE TITLE
Include additional StateClass and DeviceClass entities

### ISSUE THREAD

**Issue by jacokok** [jacokok/must-ep1800#2]
Can  we add the following for the grid and solar
        new RegisterTopic { Name = "AccumulatedChargerPower", UnitOfMeasurement = "kWh", Icon = "chart-bell-curve-cumulative", DeviceClass = "energy", StateClass = "total_increasing" },
        new RegisterTopic { Name = "AccumulatedDischargerPower", UnitOfMeasurement = "kWh", Icon = "chart-bell-curve-cumulative", DeviceClass = "energy", StateClass = "total_increasing" },
        new RegisterTopic { Name = "AccumulatedBuyPower", UnitOfMeasurement = "kWh", Icon = "chart-bell-curve-cumulative", DeviceClass = "energy", StateClass = "total_increasing" },
        new RegisterTopic { Name = "AccumulatedSellPower", UnitOfMeasurement = "kWh", Icon = "chart-bell-curve-cumulative" , DeviceClass = "energy", StateClass = "total_increasing" },
        new RegisterTopic { Name = "AccumulatedLoadPower", UnitOfMeasurement = "kWh", Icon = "chart-bell-curve-cumulative", DeviceClass = "energy", StateClass = "total_increasing" },
        new RegisterTopic { Name = "AccumulatedSelfusePower", UnitOfMeasurement = "kWh", Icon = "chart-bell-curve-cumulative", DeviceClass = "energy", StateClass = "total_increasing" },
        new RegisterTopic { Name = "AccumulatedPvsellPower", UnitOfMeasurement = "kWh", Icon = "chart-bell-curve-cumulative" , DeviceClass = "energy", StateClass = "total_increasing" },
        new RegisterTopic { Name = "AccumulatedGridChargerPower", UnitOfMeasurement = "kWh", Icon = "chart-bell-curve-cumulative" , DeviceClass = "energy", StateClass = "total_increasing" },
        new RegisterTopic { Name = "AccumulatedPvPower", UnitOfMeasurement = "kWh", Icon = "chart-bell-curve-cumulative" , DeviceClass = "energy", StateClass = "total_increasing" }

**Comment by jacokok** [comment]
@oussamaghanem

Included energy options to the requested items as well.

**Comment by oussamaghanem** [comment]
Thank you dear
Please find attached video url (we transfer) ,it's night now,and the animated power energy showing solar flow to batteries and home
Please advise

Download link
https://we.tl/t-zPZIWzTCjc

Best regards
________________________________
